/*
 * mecaviv-bridge-composesiren: C ABI of ComposeSiren's park bridge.
 *
 * Every function accepts a NULL handle and does nothing with it. Siren numbers
 * are 1..7; other numbers are ignored. The C++ wrapper mecaviv_bridge.hpp sits
 * on top of it.
 */

#ifndef MECAVIV_BRIDGE_H
#define MECAVIV_BRIDGE_H

/* Generated by cbindgen from Source/mecaviv-bridge-composesiren/src/ffi.rs when the crate
 * builds. Do not edit: change ffi.rs instead. */

#include <stdbool.h>
#include <stdint.h>

// Number of sirens: siren numbers are 1 to `MECAVIV_BRIDGE_NUM_SIRENS`.
#define MECAVIV_BRIDGE_NUM_SIRENS 7

// A siren's drive state.
typedef enum {
    // No reply from the drive, or the bridge is disabled.
    MECAVIV_ST_STATE_UNKNOWN = -1,
    // Drive disabled (standby).
    MECAVIV_ST_STATE_OFF = 0,
    // Drive enabled (ST on).
    MECAVIV_ST_STATE_ON = 1,
} mecaviv_st_state_t;

// How the park is driven.
typedef enum {
    // No transport: the handle is null, or enable failed to open one.
    MECAVIV_BRIDGE_BACKEND_NONE = 0,
    // This process talks to the boards.
    MECAVIV_BRIDGE_BACKEND_IN_PROCESS = 1,
    // `mecaviv-bridge-daemon` owns the hardware link.
    MECAVIV_BRIDGE_BACKEND_DAEMON = 2,
} mecaviv_bridge_backend_t;

// Opaque handle to a bridge.
typedef struct mecaviv_bridge_t mecaviv_bridge_t;

// Calls made to the daemon since the bridge was created. All zero when the
// bridge never used the daemon.
typedef struct {
    // Sessions opened.
    uint64_t sessions;
    // Session attempts that failed.
    uint64_t session_failures;
    // MIDI messages sent.
    uint64_t midi;
    // MIDI messages dropped because the daemon does not carry them.
    uint64_t midi_ignored;
    // Resets of one siren.
    uint64_t resets;
    // Resets of every siren.
    uint64_t reset_all;
    // ST of every siren.
    uint64_t st_all;
    // Drive-state records received.
    uint64_t drive_states;
} mecaviv_daemon_stats_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Creates a disabled bridge to the park at its default addresses. Returns
// null if its thread cannot be created.
mecaviv_bridge_t *mecaviv_bridge_new(void);

// Stops and frees a bridge.
//
// # Safety
//
// `bridge` is null or was returned by `mecaviv_bridge_new` and not freed.
// No other call on it may be running or follow.
void mecaviv_bridge_free(mecaviv_bridge_t *bridge);

// Drives the park or not. Enabling sends the reset handshake to every siren;
// disabling drops what is queued and forgets the drive states.
//
// # Safety
//
// `bridge` is null or a live handle.
void mecaviv_bridge_set_enabled(const mecaviv_bridge_t *bridge, bool enabled);

// Whether the park is driven. False for a null handle.
//
// # Safety
//
// `bridge` is null or a live handle.
bool mecaviv_bridge_is_enabled(const mecaviv_bridge_t *bridge);

// Queues a 3-byte MIDI message. Real-time safe: no lock, no allocation, no
// socket. Returns false if disabled or the queue is full. Only note off, note
// on, control change and pitch bend on channels 1 to 7 reach the sirens.
//
// # Safety
//
// `bridge` is null or a live handle.
bool mecaviv_bridge_push_midi(const mecaviv_bridge_t *bridge,
                              uint8_t status,
                              uint8_t data1,
                              uint8_t data2);

// Resets siren `siren` (1 to 7): closes its flaps, stops its motor.
//
// # Safety
//
// `bridge` is null or a live handle.
void mecaviv_bridge_reset(const mecaviv_bridge_t *bridge, uint8_t siren);

// Resets every siren.
//
// # Safety
//
// `bridge` is null or a live handle.
void mecaviv_bridge_reset_all(const mecaviv_bridge_t *bridge);

// Enables (ST on) or disables every siren's drive.
//
// # Safety
//
// `bridge` is null or a live handle.
void mecaviv_bridge_set_st_all(const mecaviv_bridge_t *bridge, bool enabled);

// The drive state of siren `siren` (1 to 7), polled from its drive once per
// second. Unknown for a null handle or another number.
//
// # Safety
//
// `bridge` is null or a live handle.
mecaviv_st_state_t mecaviv_bridge_st_state(const mecaviv_bridge_t *bridge, uint8_t siren);

// How the park is driven. While disabled, a listening daemon socket is
// reported as daemon so the UI can say what enabling will use. None for a
// null handle.
//
// # Safety
//
// `bridge` is null or a live handle.
mecaviv_bridge_backend_t mecaviv_bridge_backend(const mecaviv_bridge_t *bridge);

// Tooltip for the current backend: a static NUL-terminated string. Do not
// free it. The none tooltip for a null handle.
//
// # Safety
//
// `bridge` is null or a live handle.
const char *mecaviv_bridge_backend_tooltip(const mecaviv_bridge_t *bridge);

// Calls made to the daemon since the bridge was created. All zero for a
// null handle.
//
// # Safety
//
// `bridge` is null or a live handle.
mecaviv_daemon_stats_t mecaviv_bridge_daemon_stats(const mecaviv_bridge_t *bridge);

// The library version, `major.minor.patch`, as a static NUL-terminated
// string. Do not free it.
const char *mecaviv_bridge_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MECAVIV_BRIDGE_H */
