/*
 * mecaviv-bridge-composesiren: C ABI of ComposeSiren's park bridge.
 *
 * Every function accepts a NULL handle and does nothing with it. Siren numbers
 * are 1..7; other numbers are ignored. The C++ wrapper mecaviv_bridge.hpp sits
 * on top of it.
 */

#ifndef MECAVIV_BRIDGE_H
#define MECAVIV_BRIDGE_H

/* Generated by cbindgen from Source/mecaviv-bridge-composesiren/src/ffi.rs when the crate
 * builds. Do not edit: change ffi.rs instead. */

#include <stdbool.h>
#include <stdint.h>

// Number of sirens: siren numbers are 1 to `MECAVIV_BRIDGE_NUM_SIRENS`.
#define MECAVIV_BRIDGE_NUM_SIRENS 7

// A siren's drive state.
typedef enum {
    // No reply from the drive, or the bridge is disabled.
    MECAVIV_ST_STATE_UNKNOWN = -1,
    // Drive disabled (standby).
    MECAVIV_ST_STATE_OFF = 0,
    // Drive enabled (ST on).
    MECAVIV_ST_STATE_ON = 1,
} mecaviv_st_state_t;

// Opaque handle to a bridge.
typedef struct mecaviv_bridge_t mecaviv_bridge_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Creates a disabled bridge to the park at its default addresses. Returns
// null if its sockets or its thread cannot be created.
mecaviv_bridge_t *mecaviv_bridge_new(void);

// Stops and frees a bridge.
//
// # Safety
//
// `bridge` is null or was returned by `mecaviv_bridge_new` and not freed.
// No other call on it may be running or follow.
void mecaviv_bridge_free(mecaviv_bridge_t *bridge);

// Drives the park or not. Enabling sends the reset handshake to every siren;
// disabling drops what is queued and forgets the drive states.
//
// # Safety
//
// `bridge` is null or a live handle.
void mecaviv_bridge_set_enabled(const mecaviv_bridge_t *bridge, bool enabled);

// Whether the park is driven. False for a null handle.
//
// # Safety
//
// `bridge` is null or a live handle.
bool mecaviv_bridge_is_enabled(const mecaviv_bridge_t *bridge);

// Queues a 3-byte MIDI message. Real-time safe: no lock, no allocation, no
// socket. Returns false if disabled or the queue is full. Only note off, note
// on, control change and pitch bend on channels 1 to 7 reach the sirens.
//
// # Safety
//
// `bridge` is null or a live handle.
bool mecaviv_bridge_push_midi(const mecaviv_bridge_t *bridge,
                              uint8_t status,
                              uint8_t data1,
                              uint8_t data2);

// Resets siren `siren` (1 to 7): closes its flaps, stops its motor.
//
// # Safety
//
// `bridge` is null or a live handle.
void mecaviv_bridge_reset(const mecaviv_bridge_t *bridge, uint8_t siren);

// Resets every siren.
//
// # Safety
//
// `bridge` is null or a live handle.
void mecaviv_bridge_reset_all(const mecaviv_bridge_t *bridge);

// Enables (ST on) or disables every siren's drive.
//
// # Safety
//
// `bridge` is null or a live handle.
void mecaviv_bridge_set_st_all(const mecaviv_bridge_t *bridge, bool enabled);

// The drive state of siren `siren` (1 to 7), polled from its drive once per
// second. Unknown for a null handle or another number.
//
// # Safety
//
// `bridge` is null or a live handle.
mecaviv_st_state_t mecaviv_bridge_st_state(const mecaviv_bridge_t *bridge, uint8_t siren);

// The library version, `major.minor.patch`, as a static NUL-terminated
// string. Do not free it.
const char *mecaviv_bridge_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MECAVIV_BRIDGE_H */
