# ------------------------------------------------------------------------------
# clic-composesiren: ComposeSiren's click output (Rust, in
# Source/clic-composesiren), linked statically into ComposeSirenCore when
# COMPOSESIREN_CLIC is ON.
#
# Defines the target `clic_composesiren`, whose headers (clic_composesiren.h,
# generated by cbindgen, and the C++ wrapper clic_composesiren.hpp) are under
# the crate's include/ directory.
#
# The crate depends on the click box's engine, ClicRaspberry/rs in
# firmwares-artila, through a relative path: firmwares-artila must be checked
# out next to ComposeSiren.
#
# See cmake/RustStaticLib.cmake for the build (cargo per architecture on
# macOS, lipo when universal, Corrosion otherwise).

cmake_path(ABSOLUTE_PATH CMAKE_SOURCE_DIR NORMALIZE OUTPUT_VARIABLE _clic_cs_root)
cmake_path(GET _clic_cs_root PARENT_PATH _clic_checkouts)
if(NOT EXISTS "${_clic_checkouts}/firmwares-artila/ClicRaspberry/rs/Cargo.toml")
  message(FATAL_ERROR
    "COMPOSESIREN_CLIC is ON but firmwares-artila (with ClicRaspberry/rs) was not found at "
    "${_clic_checkouts}/firmwares-artila. Clone it next to ComposeSiren: "
    "Source/clic-composesiren/Cargo.toml depends on it by relative path.")
endif()

include("${CMAKE_SOURCE_DIR}/cmake/RustStaticLib.cmake")

composesiren_add_rust_staticlib(
  TARGET clic_composesiren
  CRATE_DIR "${CMAKE_SOURCE_DIR}/Source/clic-composesiren"
)
