# ------------------------------------------------------------------------------
# mecaviv-bridge-composesiren: ComposeSiren's park bridge (Rust, in
# Source/mecaviv-bridge-composesiren), linked statically into ComposeSirenCore
# when COMPOSESIREN_MECAVIV_BRIDGE is ON.
#
# Defines the target `mecaviv_bridge_composesiren`, whose headers
# (mecaviv_bridge.h, generated by cbindgen, and the C++ wrapper
# mecaviv_bridge.hpp) are under the crate's include/ directory.
#
# The crate depends on the mecaviv-v1 crate of mecaviv-rs through a relative
# path: mecaviv-rs must be checked out next to ComposeSiren.
#
# See cmake/RustStaticLib.cmake for the build (cargo per architecture on
# macOS, lipo when universal, Corrosion otherwise).

cmake_path(ABSOLUTE_PATH CMAKE_SOURCE_DIR NORMALIZE OUTPUT_VARIABLE _mecaviv_cs_root)
cmake_path(GET _mecaviv_cs_root PARENT_PATH _mecaviv_checkouts)
if(NOT EXISTS "${_mecaviv_checkouts}/mecaviv-rs/crates/mecaviv-v1/Cargo.toml")
  message(FATAL_ERROR
    "COMPOSESIREN_MECAVIV_BRIDGE is ON but mecaviv-rs was not found at "
    "${_mecaviv_checkouts}/mecaviv-rs. Clone it next to ComposeSiren: "
    "Source/mecaviv-bridge-composesiren/Cargo.toml depends on it by relative path.")
endif()

include("${CMAKE_SOURCE_DIR}/cmake/RustStaticLib.cmake")

composesiren_add_rust_staticlib(
  TARGET mecaviv_bridge_composesiren
  CRATE_DIR "${CMAKE_SOURCE_DIR}/Source/mecaviv-bridge-composesiren"
)

target_compile_definitions(mecaviv_bridge_composesiren INTERFACE COMPOSESIREN_MECAVIV_BRIDGE=1)
