/*
 * clic-composesiren: C ABI of ComposeSiren's click output.
 *
 * Every function accepts a NULL handle and does nothing with it. The C++
 * wrapper clic_composesiren.hpp sits on top of it.
 */

#ifndef CLIC_COMPOSESIREN_H
#define CLIC_COMPOSESIREN_H

/* Generated by cbindgen from Source/clic-composesiren/src/ffi.rs when the crate
 * builds. Do not edit: change ffi.rs instead. */

#include <stddef.h>
#include <stdint.h>

// Opaque handle to a click engine.
typedef struct clic_t clic_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// A new click engine with the built-in clicks at `sample_rate`, or null if
// it cannot be created. Free it with `clic_free`.
clic_t *clic_new(double sample_rate);

// Frees an engine from `clic_new`.
//
// # Safety
//
// `clic` is null or came from `clic_new` and is not used afterwards.
void clic_free(clic_t *clic);

// Reloads the clicks at `sample_rate` (allocates: call it from
// `prepareToPlay`, not from the audio thread).
//
// # Safety
//
// `clic` is null or a live handle from `clic_new`, not used concurrently.
void clic_set_sample_rate(clic_t *clic, double sample_rate);

// A MIDI message (`data2` is ignored for 2-byte messages). Channel 10:
// note on with note > 1 and velocity > 1 plays the strong click (even note)
// or the weak click (odd note); a program change picks the click.
//
// # Safety
//
// `clic` is null or a live handle from `clic_new`, not used concurrently.
void clic_midi(clic_t *clic, uint8_t status, uint8_t data1, uint8_t data2);

// Renders `frames` frames into `left` and `right` (overwritten).
//
// # Safety
//
// `clic` is null or a live handle from `clic_new`, not used concurrently;
// `left` and `right` are null or point to `frames` writable floats each.
void clic_render(clic_t *clic, float *left, float *right, uintptr_t frames);

// The chosen click (0 = the first), or -1 for a null handle.
//
// # Safety
//
// `clic` is null or a live handle from `clic_new`.
int32_t clic_current(const clic_t *clic);

// How many clicks there are, or 0 for a null handle.
//
// # Safety
//
// `clic` is null or a live handle from `clic_new`.
int32_t clic_count(const clic_t *clic);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CLIC_COMPOSESIREN_H */
