/*
 * composesiren-slint-ui: C ABI of the Slint editor proof of concept. The JUCE
 * side is sketched in Source/composesiren-slint-ui/juce/SlintEditor.h.
 */

#ifndef COMPOSESIREN_SLINT_UI_H
#define COMPOSESIREN_SLINT_UI_H

/* Generated by cbindgen from Source/composesiren-slint-ui/src/ffi.rs when the
 * crate builds. Do not edit: change ffi.rs instead. */

#include <stdint.h>
#include <stdbool.h>

// Pointer event kinds for [`cs_slint_ui_pointer`].
typedef enum {
    // Mouse button down.
    CS_POINTER_DOWN,
    // Mouse button up.
    CS_POINTER_UP,
    // Mouse moved or dragged.
    CS_POINTER_MOVE,
    // Mouse left the editor.
    CS_POINTER_EXIT,
} CsPointer;

// An editor owned by the plugin (opaque).
typedef struct CsSlintUi CsSlintUi;

// Callbacks from the editor to the plugin. `context` is handed back unchanged.
typedef struct {
    // The plugin's editor object.
    void *context;
    // A parameter moved: index into the parameter table, value in the parameter's own range.
    void (*param_changed)(void *context, uint32_t param, float value);
    // A gesture on a parameter begins (`true`) or ends (`false`).
    void (*gesture)(void *context, uint32_t param, bool begin);
    // The siren type changed (0 Alto, 1 Bass, 2 Tenor, 3 Soprano, 4 Piccolo).
    void (*category_changed)(void *context, uint32_t category);
    // A key of the on-screen keyboard went down or up.
    void (*note)(void *context, uint8_t note, bool on);
} CsSlintUiCallbacks;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Create an editor at `scale` physical pixels per logical pixel. Null when Slint cannot create it.
CsSlintUi *cs_slint_ui_new(CsSlintUiCallbacks callbacks, float scale);

// Destroy an editor made by [`cs_slint_ui_new`] (null is ignored).
//
// # Safety
// `ui` comes from `cs_slint_ui_new` and is not used afterwards.
void cs_slint_ui_free(CsSlintUi *ui);

// Width of the pixel buffer [`cs_slint_ui_tick`] draws into.
//
// # Safety
// `ui` is a live editor.
uint32_t cs_slint_ui_width(const CsSlintUi *ui);

// Height of the pixel buffer [`cs_slint_ui_tick`] draws into.
//
// # Safety
// `ui` is a live editor.
uint32_t cs_slint_ui_height(const CsSlintUi *ui);

// The host changed a parameter (automation, preset, MIDI input). The editor shows it on its next tick.
//
// # Safety
// `ui` is a live editor.
void cs_slint_ui_set_param(const CsSlintUi *ui,
                           uint32_t param,
                           float value);

// Run timers and animations; redraw into `pixels` (BGRA premultiplied, `juce::Image::ARGB`; `stride` pixels
// per row, at least width x height) when something changed. True when redrawn.
//
// # Safety
// `ui` is a live editor; `pixels` holds `stride * height` pixels.
bool cs_slint_ui_tick(const CsSlintUi *ui,
                      uint8_t *pixels,
                      uint32_t stride);

// Forward a pointer event at logical coordinates.
//
// # Safety
// `ui` is a live editor.
void cs_slint_ui_pointer(const CsSlintUi *ui, CsPointer kind, float x, float y);

// Forward a wheel event (logical pixels).
//
// # Safety
// `ui` is a live editor.
void cs_slint_ui_wheel(const CsSlintUi *ui, float x, float y, float dx, float dy);

// Show the siren type chosen elsewhere (state restore, `VoiceManagerState::Listener`). Not reported back
// through `category_changed`, so the plugin's listener does not loop.
//
// # Safety
// `ui` is a live editor.
void cs_slint_ui_set_category(const CsSlintUi *ui,
                              uint32_t category);

// Number of parameters in the table (indices `0..count`).
uint32_t cs_slint_ui_param_count(void);

// The parameter's code name (`Volume`): the plugin's id is `"<siren> | <code name>"`. Null past the end.
const char *cs_slint_ui_param_code_name(uint32_t param);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* COMPOSESIREN_SLINT_UI_H */
