/*
 * composesiren-record: C ABI of ComposeSiren's recorder (FLAC or WAV of the
 * audio output). The C++ wrapper sits in
 * ComposeSirenCore/lib/utilities/recorder/Recorder.
 */

#ifndef COMPOSESIREN_RECORD_H
#define COMPOSESIREN_RECORD_H

/* Generated by cbindgen from Source/composesiren-record/src/ffi.rs when the
 * crate builds. Do not edit: change ffi.rs instead. */

#include <stdint.h>

// Samples per FLAC frame (the reference encoder's default).
#define BLOCK_SIZE 4096

// Opaque recorder.
typedef struct cs_rec_t cs_rec_t;

// Where a recording stands (see `cs_rec_status`).
typedef struct {
    // 1 while recording.
    int recording;
    // 0 FLAC 24-bit, 1 WAV 24-bit, 2 WAV 32-bit float; -1 before any recording.
    int format;
    // The recording's sample rate, in Hz.
    uint32_t sample_rate;
    // The recording's channels.
    uint32_t channels;
    // Frames written to the file so far.
    uint64_t frames_written;
    // Frames the audio thread could not hand over.
    uint64_t frames_dropped;
    // 1 if the writer stopped on an error (see `cs_rec_error`).
    int failed;
} cs_rec_status_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// A new recorder, not recording. Free it with `cs_rec_destroy`.
cs_rec_t *cs_rec_create(void);

// Stops a running recording (completing its file) and frees the recorder.
//
// # Safety
//
// `rec` is null or from `cs_rec_create`, not yet destroyed, and no other
// call on it is running or follows.
void cs_rec_destroy(cs_rec_t *rec);

// The audio thread's output block: `channels` pointers to `frames` samples.
// Copies it when recording. Allocates nothing, takes no lock. Call it from one
// thread at a time (the audio thread).
//
// # Safety
//
// `rec` is valid; `data` holds `channels` pointers, each to `frames` floats.
void cs_rec_process(const cs_rec_t *rec,
                    const float *const *data,
                    uint32_t channels,
                    uint32_t frames);

// Starts recording to `path` (UTF-8, null-terminated) in `format` (0 FLAC
// 24-bit, 1 WAV 24-bit, 2 WAV 32-bit float), for blocks of `channels`
// channels at `sample_rate`. Returns 0, or -1 with the reason in `error`.
//
// # Safety
//
// `rec` is valid; `path` is null-terminated; `error` has room for
// `error_len` bytes, or is null.
int cs_rec_start(const cs_rec_t *rec,
                 const char *path,
                 uint32_t format,
                 uint32_t sample_rate,
                 uint32_t channels,
                 char *error,
                 uint32_t error_len);

// Stops recording and completes the file. Returns 0, or -1 with the reason
// in `error` (nothing was recording, or the writer failed).
//
// # Safety
//
// As for `cs_rec_start`.
int cs_rec_stop(const cs_rec_t *rec, char *error, uint32_t error_len);

// The running recording, or the last one.
//
// # Safety
//
// `rec` is valid and `out` writable.
void cs_rec_status(const cs_rec_t *rec, cs_rec_status_t *out);

// The running or last recording's file path, null-terminated in `out`.
// Returns its length (0 before any recording).
//
// # Safety
//
// `rec` is valid; `out` has room for `len` bytes, or is null.
uint32_t cs_rec_path(const cs_rec_t *rec, char *out, uint32_t len);

// The writer's last error, null-terminated in `out`. Returns its length.
//
// # Safety
//
// As for `cs_rec_path`.
uint32_t cs_rec_error(const cs_rec_t *rec, char *out, uint32_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* COMPOSESIREN_RECORD_H */
