[package]
name = "composesiren-dsp-rs-lib"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["staticlib"]


[[bin]]
name = "composesiren-dsp-rs-main"
path = "src/main.rs"
#
[dependencies]
fable_library_rust = { path = "../generated/rust/mecaviv-siren-declarations-rs/src/fable_modules/fable-library-rust" }
mecaviv-siren-declarations-rs = { path = "../generated/rust/mecaviv-siren-declarations-rs"}
bytemuck = { version = "*", features = ["extern_crate_alloc"]}
lazy_static = "*"
ndarray = "*"
byteorder = "*"


[build-dependencies]
cmake = "*"
cbindgen = "*"