# ------------------------------------------------------------------------------
# What the About dialog shows about the build: the project's CMake options, and
# the git branch and commit.
#
# In the project (include() this file before the first option):
#
#   composesiren_option(NAME "help" ON|OFF)    like option(), and remembers NAME
#   composesiren_add_build_info()              target ComposeSirenBuildInfo,
#                                              the header generated/BuildInfo.h
#
# The target runs this same file as a script (cmake -P) on every build, so the
# commit is the one being built, not the one at configure time. The header is
# rewritten only if its content changes, so an unchanged tree rebuilds nothing.
# See Source/Plugins/SirenOrchestra/AboutDialog for the reader.

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)

  # Script mode. Inputs: OUT, SRC, OPTIONS ("NAME=VALUE;..."), VERSION, BUILD_TYPE.
  function(_bi_git out)
    execute_process(COMMAND git ${ARGN} WORKING_DIRECTORY "${SRC}"
      OUTPUT_VARIABLE value OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET RESULT_VARIABLE status)
    if(NOT status EQUAL 0)
      set(value "")
    endif()
    set(${out} "${value}" PARENT_SCOPE)
  endfunction()

  _bi_git(commit rev-parse HEAD)
  _bi_git(branch branch --show-current)
  _bi_git(modified status --porcelain --untracked-files=no)
  _bi_git(remote remote get-url origin)
  _bi_git(pushed for-each-ref --contains HEAD refs/remotes) # no network: refs as last fetched

  # A link only when GitHub can show the commit: origin is on GitHub and a
  # remote-tracking branch contains it.
  set(url "")
  if(commit AND pushed AND remote MATCHES "github\\.com[:/]([^/]+/[^/]+)$")
    string(REGEX REPLACE "\\.git$" "" repo "${CMAKE_MATCH_1}")
    set(url "https://github.com/${repo}/commit/${commit}")
  endif()
  set(dirty false)
  if(modified)
    set(dirty true)
  endif()

  set(options "")
  foreach(entry IN LISTS OPTIONS)
    string(REGEX MATCH "^([^=]*)=(.*)$" _ "${entry}")
    string(APPEND options "    {\"${CMAKE_MATCH_1}\", \"${CMAKE_MATCH_2}\"},\n")
  endforeach()

  file(CONFIGURE OUTPUT "${OUT}" @ONLY CONTENT [[
// Generated by cmake/BuildInfo.cmake. Do not edit.
#pragma once

namespace cs::buildinfo {

struct Option { const char* name; const char* value; };

inline constexpr Option options[] = {
@options@};
inline constexpr const char* version = "@VERSION@";
inline constexpr const char* buildType = "@BUILD_TYPE@";
inline constexpr const char* branch = "@branch@";
inline constexpr const char* commit = "@commit@";
inline constexpr bool dirty = @dirty@;
// Empty unless the commit is on GitHub.
inline constexpr const char* commitUrl = "@url@";

} // namespace cs::buildinfo
]])
  return()
endif()

# Project mode.

set_property(GLOBAL PROPERTY COMPOSESIREN_OPTIONS "")

macro(composesiren_option name help default)
  option(${name} "${help}" ${default})
  set_property(GLOBAL APPEND PROPERTY COMPOSESIREN_OPTIONS ${name})
endmacro()

function(composesiren_add_build_info)
  get_property(names GLOBAL PROPERTY COMPOSESIREN_OPTIONS)
  set(options "")
  foreach(name IN LISTS names)
    list(APPEND options "${name}=${${name}}")
  endforeach()

  set(header "${CMAKE_BINARY_DIR}/generated/BuildInfo.h")
  add_custom_target(ComposeSirenBuildInfo ALL
    COMMAND "${CMAKE_COMMAND}"
      "-DOUT=${header}"
      "-DSRC=${CMAKE_SOURCE_DIR}"
      "-DOPTIONS=${options}"
      "-DVERSION=${PROJECT_VERSION}${PROJECT_VERSION_SUFFIX}"
      "-DBUILD_TYPE=$<CONFIG>"
      -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
    BYPRODUCTS "${header}"
    COMMENT "Generating BuildInfo.h"
    VERBATIM)
endfunction()
