/*
 * composesiren-mcp: C ABI of ComposeSiren's in-process MCP server.
 *
 * The server listens on 127.0.0.1 and records itself in ~/.composesiren_mcp.json,
 * the same kind of discovery file Gearmulator writes at ~/.gearmulator_mcp.json.
 * The C++ wrapper sits in ComposeSirenCore/McpControl.
 */

#ifndef COMPOSESIREN_MCP_H
#define COMPOSESIREN_MCP_H

/* Generated by cbindgen from Source/composesiren-mcp/src/ffi.rs when the crate
 * builds. Do not edit: change ffi.rs instead. */

#include <stdint.h>

// Opaque server. Null means it failed to start.
typedef struct cs_mcp_server_t cs_mcp_server_t;

// C function implemented by the plugin.
//
// `request_json` is a null-terminated UTF-8 JSON object. The return value is
// a `malloc`'d null-terminated UTF-8 JSON object, which Rust frees.
typedef char *(*DispatchFn)(const char*, void*);

// Plugin callback. `request_json` is one JSON object. The return value is a
// `malloc`'d JSON object; the server frees it with `free`.
typedef DispatchFn cs_mcp_dispatch_fn;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Start the server. `out_port` receives the bound port. Returns null on failure.
//
// # Safety
//
// `plugin_name` and `plugin_4cc` are null-terminated UTF-8 and live for the
// call. `dispatch` and `user` stay valid until `cs_mcp_stop`. `out_port` is
// writable. `standalone` is 0 or 1.
cs_mcp_server_t *cs_mcp_start(const char *plugin_name,
                              const char *plugin_4cc,
                              int standalone,
                              cs_mcp_dispatch_fn dispatch,
                              void *user,
                              int *out_port);

// Stop the server and remove its discovery entry.
//
// # Safety
//
// `server` is null or was returned by `cs_mcp_start` and not stopped. No other
// call on it follows.
void cs_mcp_stop(cs_mcp_server_t *server);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* COMPOSESIREN_MCP_H */
